name: travel_trackr
description: Travel Trackr
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  firebase_core: ^2.13.0
  get_it: ^7.2.0
  injectable: ^1.5.4
  freezed_annotation: ^2.2.0
  auto_route: ^7.1.0
  flutter_bloc: ^8.1.1
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.7.1
  device_info_plus: ^3.2.3
  get_storage: ^2.0.3
  retrofit: ^3.3.1
  fresh_dio: ^0.3.1
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.5
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  auto_route_generator: ^7.0.0
  flutter_launcher_icons: ^0.13.1
  retrofit_generator: ^4.2.0

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21

#flutter pub run intl_utils:generate
flutter_intl:
  main_locale: en
  enabled: true
  arb_dir: lib/core/l10n
  output_dir: lib/core/l10n/generated

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data/