// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Vsz-RETifIhbvgPeIfkupzx--vPaBGc',
    appId: '1:136895599453:android:dac1b2b9c3f3ef02c20eb4',
    messagingSenderId: '136895599453',
    projectId: 'travel-trackr',
    databaseURL: 'https://travel-trackr-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-trackr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtVnGavq9IqAaBLEN0AXKntRUKi0_n8YI',
    appId: '1:136895599453:ios:273e7997119905a1c20eb4',
    messagingSenderId: '136895599453',
    projectId: 'travel-trackr',
    databaseURL: 'https://travel-trackr-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'travel-trackr.appspot.com',
    iosClientId: '136895599453-3f1nkfrdqoe39nqdm8md970m8parg28d.apps.googleusercontent.com',
    iosBundleId: 'app.travelTrackr.net',
  );
}
